#pragma once

//specials

//normal
#include "../Days/Day1/Day1.h"
#include "../Days/Day2/Day2.h"
#include "../Days/Day3/Day3.h"
#include "../Days/Day4/Day4.h"
#include "../Days/Day5/Day5.h"
#include "../Days/Day6/Day6.h"
#include "../Days/Day7/Day7.h"
#include "../Days/Day8/Day8.h"
#include "../Days/Day9/Day9.h"
#include "../Days/Day10/Day10.h"
#include "../Days/Day11/Day11.h"
#include "../Days/Day12/Day12.h"
#include "../Days/Day13/Day13.h"
#include "../Days/Day14/Day14.h"
#include "../Days/Day15/Day15.h"
#include "../Days/Day16/Day16.h"
#include "../Days/Day17/Day17.h"
#include "../Days/Day18/Day18.h"
#include "../Days/Day19/Day19.h"
#include "../Days/Day20/Day20.h"
#include "../Days/Day21/Day21.h"
#include "../Days/Day22/Day22.h"
#include "../Days/Day23/Day23.h"
#include "../Days/Day24/Day24.h"
#include "../Days/Day25/Day25.h"